source :rubygems
gem 'sinatra'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'mustache'
gem 'i18n'
gem 'sass', '3.1.0.alpha.249'
gem 'compass', '0.11.beta.3'
gem 'compass-susy-plugin', '0.9.beta.3'
gem 'fancy-buttons', '1.1.0.alpha.1'
